### ISSUE TITLE
Active notifications not shown correctly

### ISSUE THREAD

**Issue by SBerenji** [Sudhan-Dahake/CalamityCall#167]
**Issue:** The 'Active' tab under the 'Alerts' page is not correctly demonstrating the active alerts.

**Steps to Reproduce:**
1. Go to the 'Alerts' page by clicking on the corresponding button from the bottom navigation menu
2. Observe the static notifications in the Active tab

**Expected Behavior:**
It is expected that the Alert tab to only show the notifications in the past 24 hours as active notifications

**Actual Behavior:**
As can be seen from the image below, currently the 'Active' tab is only demonstrating two placeholder notifications which are static and always there meaning they are not the actual active alerts. 

![Capture](https://github.com/user-attachments/assets/49a98de8-ecf9-4b92-843f-96323d300ee8)

**Comment by Sudhan-Dahake** [comment]
Hi Saba,

Thank you for raising this issue. The issue persisted because the server had no logic to handle active notifications. I implemented endpoints that when accessed scans the database for notifications that were issued within 24 hours and compiles them in a list and send it to the app.

This is the format it sends it in:

{
    Notifications: [Notification1, Notification2, ..............]
}


I would also like to mention that Owen Covach took care of receiving the active packet on the front-end side and parsing it correctly.

Also thank you Saba for designing the active page that was easily integrable and scalable.
