### ISSUE TITLE
Preferences not saving flashing and notification type as expected

### ISSUE THREAD

**Issue by SBerenji** [Sudhan-Dahake/CalamityCall#176]
Issue: The preferences feature is not saving the notification type and flashing type correctly.

Steps to reproduce:
1. Go to the settings page
2. Log in using an existing account
3. Change the notification type
4. Close the app 
5. Reopen the app 
6. Observer how the settings page has not saved the previous notification type selected

Expected behavior: It is expected that the settings page to correctly save the notification types chosen by the user.

**Comment by serb2341** [comment]
This bug was fixed by changing line 55 to this on both the FlashingActivity page and NotificationTypeActivity: sharedPreferences = getSharedPreferences("NotificationPreferences", MODE_PRIVATE);. 
The previous line was sharedPreferences = getSharedPreferences("FlashingPreferences", MODE_PRIVATE);, and sharedPreferences = getSharedPreferences("NotificationTypePreferences", MODE_PRIVATE);
